name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["12.14.1"]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    name: node.js ${{ matrix.node }} test in ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Environment
        run: |
          node -v
          npm -v
          yarn --version

      - name: Install
        run: |
          yarn

      - name: Lint
        run: |
          npm run lint

      - name: Compile
        run: |
          yarn run compile

      - name: Package
        run: |
          npx vsce package -o ./vscode-gpm.vsix

      - uses: actions/upload-artifact@v1
        if: runner.os == 'linux'
        with:
          name: package
          path: ./vscode-gpm.vsix

  release:
    runs-on: ubuntu-latest
    name: "Release to vscode market and github"
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: build
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: package

      - uses: softprops/action-gh-release@v1
        name: publish to Github
        env:
          # require Github Personal Access Token
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          files: |
            ./package/vscode-gpm.vsix
          draft: false

      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: publish to vscode market
        # require Azure DevOps Personal Access Token
        run: npx vsce publish --packagePath ./package/vscode-gpm.vsix --pat ${{ secrets.ADO_TOKEN }}
